export const data = [
    [
        { img: './images/Gallery/AWIC/1.jpg', title: 'AWIC' },
        { img: './images/Gallery/AWIC/2.jpg' },
        { img: './images/Gallery/AWIC/3.jpg' },
        { img: './images/Gallery/AWIC/4.jpg' },
        { img: './images/Gallery/AWIC/5.jpg' },
        { img: './images/Gallery/AWIC/6.jpg' },
        { img: './images/Gallery/AWIC/7.jpg' },
        { img: './images/Gallery/AWIC/8.jpg' },
    ],
    [
        { img: './images/Gallery/IndiaBulls/1.jpg', title: 'India Bulls' },
        { img: './images/Gallery/IndiaBulls/2.jpg' },
        { img: './images/Gallery/IndiaBulls/3.jpg' },
        { img: './images/Gallery/IndiaBulls/4.jpg' },
        { img: './images/Gallery/IndiaBulls/5.jpg' },
        { img: './images/Gallery/IndiaBulls/6.jpg' },
    ],
    [
        { img: './images/Gallery/Retrofitting/1.jpg', title: 'Repair and Rehabilitation' },
        { img: './images/Gallery/Retrofitting/2.jpg' },
        { img: './images/Gallery/Retrofitting/3.jpg' },
        { img: './images/Gallery/Retrofitting/4.jpg' },
        { img: './images/Gallery/Retrofitting/5.jpg' },
    ],
    [
        { img: './images/Gallery/TataHousing/1.jpeg', title: 'Tata Housing' },
        { img: './images/Gallery/TataHousing/2.jpeg' },
        { img: './images/Gallery/TataHousing/3.jpg' },
        { img: './images/Gallery/TataHousing/4.jpeg' },
        { img: './images/Gallery/TataHousing/5.jpeg' },
        { img: './images/Gallery/TataHousing/6.jpg' },
    ],
    [
        { img: './images/Gallery/vatika/1.jpg', title: 'Vatika' },
        { img: './images/Gallery/vatika/2.jpg' },
        { img: './images/Gallery/vatika/3.jpg' },
        { img: './images/Gallery/vatika/4.jpg' },
        { img: './images/Gallery/vatika/5.jpg' },
        { img: './images/Gallery/vatika/6.jpg' },
        { img: './images/Gallery/vatika/7.jpg' },
        { img: './images/Gallery/vatika/8.jpg' },
    ],
    [
        { img: './images/Gallery/Airport/1.jpg', title: 'Airport' },
        { img: './images/Gallery/Airport/2.jpg' },
        { img: './images/Gallery/Airport/3.jpg' },
        { img: './images/Gallery/Airport/4.jpg' },
        { img: './images/Gallery/Airport/5.jpg' },
        { img: './images/Gallery/Airport/6.jpg' },
        { img: './images/Gallery/Airport/7.jpg' },
        { img: './images/Gallery/Airport/8.jpg' },
        { img: './images/Gallery/Airport/9.jpg' },
        { img: './images/Gallery/Airport/10.jpg' },
        { img: './images/Gallery/Airport/11.jpg' },
        { img: './images/Gallery/Airport/12.jpg' },
        { img: './images/Gallery/Airport/13.jpg' },
        { img: './images/Gallery/Airport/14.jpg' },
        { img: './images/Gallery/Airport/15.jpg' },
        { img: './images/Gallery/Airport/16.jpg' },
        { img: './images/Gallery/Airport/17.jpg' },
        { img: './images/Gallery/Airport/18.jpg' },
        { img: './images/Gallery/Airport/19.jpg' },
        { img: './images/Gallery/Airport/20.jpg' },
        { img: './images/Gallery/Airport/21.jpg' },
        { img: './images/Gallery/Airport/22.jpg' },
       
    ],
    [
        { img: './images/Gallery/EpoxyFlooring/1.jpg', title: 'Epoxy Flooring' },
        { img: './images/Gallery/EpoxyFlooring/2.jpg' },
        { img: './images/Gallery/EpoxyFlooring/3.jpg' },
        { img: './images/Gallery/EpoxyFlooring/4.jpg' },
        { img: './images/Gallery/EpoxyFlooring/5.jpg' },
        { img: './images/Gallery/EpoxyFlooring/6.jpg' },
    ],
    [
        { img: './images/Gallery/FormulaOne/1.jpg', title: 'Formula One' },
        { img: './images/Gallery/FormulaOne/2.jpg' },
        { img: './images/Gallery/FormulaOne/3.jpg' },
        { img: './images/Gallery/FormulaOne/4.jpg' },
        { img: './images/Gallery/FormulaOne/5.jpg' },
    ],
    [
        { img: './images/Gallery/Infra/1.jpg', title: 'Infra' },
        { img: './images/Gallery/Infra/2.jpg' },
        { img: './images/Gallery/Infra/3.jpg' },
    ],
    [
        { img: './images/Gallery/Metro/1.jpg', title: 'Metro' },
        { img: './images/Gallery/Metro/2.jpg' },
        { img: './images/Gallery/Metro/3.jpg' },
        { img: './images/Gallery/Metro/4.jpg' },
        { img: './images/Gallery/Metro/5.jpg' },
        { img: './images/Gallery/Metro/6.jpg' },
        { img: './images/Gallery/Metro/7.jpg' },
        { img: './images/Gallery/Metro/8.jpg' },
        { img: './images/Gallery/Metro/9.jpg' },
        { img: './images/Gallery/Metro/10.jpg' },
        { img: './images/Gallery/Metro/11.jpg' },
        { img: './images/Gallery/Metro/12.jpg' },
        { img: './images/Gallery/Metro/13.jpg' },
        { img: './images/Gallery/Metro/14.jpg' },
        { img: './images/Gallery/Metro/15.jpg' },
        { img: './images/Gallery/Metro/16.jpg' },
        { img: './images/Gallery/Metro/17.jpg' },
        { img: './images/Gallery/Metro/18.jpg' },
        { img: './images/Gallery/Metro/19.jpg' },
        { img: './images/Gallery/Metro/20.jpg' },
        { img: './images/Gallery/Metro/21.jpg' },
        { img: './images/Gallery/Metro/22.jpg' },
        { img: './images/Gallery/Metro/23.jpg' },
        { img: './images/Gallery/Metro/24.jpg' },
        { img: './images/Gallery/Metro/25.jpg' },
        { img: './images/Gallery/Metro/26.jpg' },
        { img: './images/Gallery/Metro/27.jpg' },
    ],
]